# Generated by Django 3.2.8 on 2021-10-08 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AfterUpgrade_Internet', models.IntegerField()),
                ('AfterUpgrade_Facebook', models.IntegerField()),
                ('AfterUpgrade_YouTube', models.IntegerField()),
                ('AfterUpgrade_BDInternet', models.IntegerField()),
                ('upgrade_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(upload_to='')),
                ('details', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_name', models.CharField(max_length=150)),
                ('Existing_Internet', models.IntegerField()),
                ('Existing_Facebook', models.IntegerField()),
                ('Existing_YouTube', models.IntegerField()),
                ('Existing_BDInternet', models.IntegerField()),
                ('Upgrade_Internet', models.IntegerField()),
                ('Upgrade_Facebook', models.IntegerField()),
                ('Upgrade_YouTube', models.IntegerField()),
                ('Upgrade_BDInternet', models.IntegerField()),
                ('data_show', models.BooleanField(default=False)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandwidth.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandwidth.category')),
            ],
        ),
    ]
