# Generated by Django 3.2.8 on 2021-10-09 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bandwidth.article'),
            preserve_default=False,
        ),
    ]
