# Generated by Django 3.2.8 on 2021-10-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0002_upgrade_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='upgrade_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
